# This file was generated by GoReleaser. DO NOT EDIT.
cask "rel" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "95fa54170a8689cebc7bc04911ef42a5eef84a794a22a7269c51b0a0f697dfa3"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8c4fff24e32e3c63c60b980066a6f333bcdb5e4d48f19044d4dec219e3b88af4"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7018f4d591ae3b18b1216852ef491070b9eb6cf8b7eb27abe86e246dc6f8d547"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "04d728782a9f8a613dd916f4836b4f94327ba7d9158e5d1c169dc6c691d41116"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rel"
  desc "TUI tool that automates periodic GitHub release processes"
  homepage "https://github.com/gozeloglu/rel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rel"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rel"]
    end
  end
  generate_completions_from_executable "bin/rel", "completion",
    base_name: "rel",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    Set a GitHub token before using rel:

      export GH_TOKEN="your_github_token_here"

    Then run 'rel init' once to create a profile.
  EOS
end
