# This file was generated by GoReleaser. DO NOT EDIT.
cask "rel" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "6d533200e7bbbd629d66be049787d2b10ca426c29a8073922ccf8196070ff647"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "333a4baf1c676160d9da4d1c3cde6c24db43c91635bc5d9da4ce50d93282a45d"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8d2d3b180bf0a1cf588032a5b94901c2269cd00bad09f4f55c3718bcace92f2a"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "993d8d7bff70555f727b2a29fd79023c45c4cf4bfda11a9b7df18e47e2799a60"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rel"
  desc "TUI tool that automates periodic GitHub release processes"
  homepage "https://github.com/gozeloglu/rel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rel"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rel"]
    end
  end
  generate_completions_from_executable "bin/rel", "completion",
    base_name: "rel",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    Set a GitHub token before using rel:

      export GH_TOKEN="your_github_token_here"

    Then run 'rel init' once to create a profile.
  EOS
end
