# This file was generated by GoReleaser. DO NOT EDIT.
cask "rel" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "52a27623bdd0b0437cbabc16ce969c70b98b8eff445642d81c0da7afe705c101"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4a2a635bc19df554e1e8232bd24e00f1daaf8b01aed2335988c5f082a4b6a44e"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bedb0d2b99cbb5aa31a91e5d414e3acafd600f62f28b8d4a6f807d4342eda3d7"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ab6c7a32e1618a32b340e9c201f985ee3c8f1fc7dade7cee184e3d0efec335f1"
      url "https://github.com/gozeloglu/rel/releases/download/v#{version}/rel_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rel"
  desc "TUI tool that automates periodic GitHub release processes"
  homepage "https://github.com/gozeloglu/rel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rel"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rel"]
    end
  end
  generate_completions_from_executable "bin/rel", "completion",
    base_name: "rel",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    Set a GitHub token before using rel:

      export GH_TOKEN="your_github_token_here"

    Then run 'rel init' once to create a profile.
  EOS
end
