# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "9b2389eaf0dada96f15df2c5de1adcad08f526af492045dbe7377ff29efe5453"
      url "https://github.com/gozeloglu/semver/releases/download/v#{version}/semver_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "899f9f006fffe9add5e96b745a4c82576d5710e57835b73c8eb5284a73f3d83f"
      url "https://github.com/gozeloglu/semver/releases/download/v#{version}/semver_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7de42a8686ee79eba5829b8df469ae47ac6ed075ff1aa706869d723fbd5f8bdf"
      url "https://github.com/gozeloglu/semver/releases/download/v#{version}/semver_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "152bb3f63445ea84d220da075fdc5b91b0c2221c7a1dae9307328de101d529df"
      url "https://github.com/gozeloglu/semver/releases/download/v#{version}/semver_#{version}_linux_amd64.tar.gz"
    end
  end

  name "semver"
  desc "A CLI tool to manage semantic versioning with tags and pushes"
  homepage "https://github.com/gozeloglu/semver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/semver"]
    end
  end

  # No zap stanza required
end
