# This file was generated by GoReleaser. DO NOT EDIT.
cask "semver" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "f646e24eb31acaddc488f71901cd31099fac530c61f0643d424b61d293c2045b"
      url "https://github.com/gozeloglu/semver/releases/download/v#{version}/semver_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "53c6583e316398a89503fc7c7323a6ae574fa27ebc4d8b1f909f685aed62c6e0"
      url "https://github.com/gozeloglu/semver/releases/download/v#{version}/semver_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b005228722833ffda8a9e77f0c76a91540e18f74fcc90f1fcc1ac8e6fb0eda75"
      url "https://github.com/gozeloglu/semver/releases/download/v#{version}/semver_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7f3e109e0dd770a21216a23bfc5d81b64d4310248c0c77acd72f165908cf36ff"
      url "https://github.com/gozeloglu/semver/releases/download/v#{version}/semver_#{version}_linux_amd64.tar.gz"
    end
  end

  name "semver"
  desc "A CLI tool to manage semantic versioning with tags and pushes"
  homepage "https://github.com/gozeloglu/semver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semver"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/semver"]
    end
  end

  # No zap stanza required
end
